### ISSUE TITLE
wrong line endings

### ISSUE THREAD

**Issue by ruv** [irdvo/ffl#5]
It seems that commit 878d905 brings some issue with line endings in the following files
engines/VFXForth/config.fs
engines/Win32Forth/config.fs
engines/lxf/config.fs

Line endings now are: 0xD 0xD 0xA
I suggest to quickly rewrite history and re-push this commit with --force flag.

**Comment by irdvo** [comment]
Thanks,

I fixed it.

2016-09-12 16:16 GMT+02:00 ruv <notifications@github.com>:

**Comment by ruv** [comment]
If somebody has caught the wrong commit, it needs to be reset to avoid conflict:

```
git reset --hard 878d905^ # note that this command will erase local changes
git pull

```
