### ISSUE TITLE
tlb requires #bits/cell from config

### ISSUE THREAD

**Issue by jephthai** [irdvo/ffl#6]
I noticed, testing with gforth, that if I include `ffl/tlb.fs` to get the toolbelt words, I get an error:

    $ gforth
    Gforth 0.7.3, Copyright (C) 1995-2008 Free Software Foundation, Inc.
    Gforth comes with ABSOLUTELY NO WARRANTY; for details type `license'
    Type `bye' to exit
    include ffl/tlb.fs 
    /Users/jstone/src/ffl/ffl/tlb.fs:87: Undefined word

But if I include `ffl/config.fs` first, then it works, because that file defines the `#bits/cell` word.  As a Forth newb, I'm not sure if it's desirable to add `include ffl/config.fs` at the top of `ffl/tlb.fs`, but I thought I'd mention it.

**Comment by irdvo** [comment]
It is not the purpose of the toolbelt module to be directly included in a
program.

For every forth engine that is supported by the ffl, there is a config.fs
file. I noticed that there were a number of words that are repeated in
these config.fs files. So I took the words that can be written in forth and
are present in the config.fs files and put them in the toolbelt module. The
config.fs file then includes the toolbelt module.

So, if you want to use one of the toolbelt words,  you include the
config.fs for your forth engine.



2017-02-07 1:42 GMT+01:00 Josh Stone <notifications@github.com>:
