### ISSUE TITLE
gsv needs updates for new param types

### ISSUE THREAD

**Issue by poldy** [irdvo/ffl#7]
After some hiatus, gtk-server is now under active development again. I wanted to try out the Motif interface, but hit a problem. Functions like XtVaSetValues use a new "VARARGS" parameter type in gtk-server.cfg . "DATA", "ENUM" and "CLASS" are also unrecognised by gsv.fs .

**Comment by irdvo** [comment]
The documentation is updated [GTKserver](http://http://irdvo.nl/FFL/GTKserver.html)
