### ISSUE TITLE
Glade with  gtk-server

### ISSUE THREAD

**Issue by PeterForth** [irdvo/ffl#9]
Dear Irvo, thanks for your great contrib to forth programming.
We are having an issue with GTK porting to our project Forth.

At the moment we are using GTK-server over tcp, for fast development.
We use GLADE. We can read well any GLADE 3.6 file with buttons, labels,
etc. 
1) We need a simple glade file consisting of a window  with any picture inside. 
2) Then your gforth code which functions you use to open the file and show up 
that picture.

Thanks in advance for your help !
Kind regards
Peter

**Comment by irdvo** [comment]
Hello,

No, I have never used glade with the gtk-server (or otherwise), so I am
afraid that I can't help you with that.

Perhaps that the gtk-server team can give you some tips.

Greetings,
Dick


Op wo 10 jul. 2019 om 16:54 schreef PeterForth <notifications@github.com>:

**Comment by PeterForth** [comment]
Thank you Dick for your kind answer !

for my luck  I could find the problem it was my PATH to GTK\BIN
windows installation of GTK is very strange...

Cheers
Peter
